--Ejercicio 01, 02 y 03_13
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE PERMITS CASCADE CONSTRAINTS;

CREATE TABLE PERSONA (
    id_persona NUMBER PRIMARY KEY,
    nombre VARCHAR(100),
    contrasenia VARCHAR(100),
    tipo VARCHAR(1) CHECK (tipo IN ('A', 'U')),
    baneado NUMBER(1,0)
);

INSERT INTO persona (id_persona, nombre, contrasenia,tipo,baneado) VALUES (1, 'Admin1', '1234','A',0);

CREATE TABLE Permits (
    id_persona INT PRIMARY KEY,
    piramide NUMBER NOT NULL CHECK (piramide IN (0, 1)),
    tres_en_raya NUMBER NOT NULL CHECK (tres_en_raya IN (0, 1)),
    dado NUMBER NOT NULL CHECK (dado IN (0, 1)),
    FOREIGN KEY (id_persona) REFERENCES PERSONA(id_persona)
);

SELECT * FROM PERSONA;

SELECT * FROM Permits;

--Ejercicio 04_13

DROP TABLE cliente CASCADE CONSTRAINTS;

CREATE TABLE cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_completo VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    telefono VARCHAR2(20) NOT NULL,
    fecha_nacimiento VARCHAR2 (20) NOT NULL
);

SELECT * FROM cliente;

SELECT * FROM cliente WHERE nombre_completo LIKE '%' ||asdfa ||'%';
